INSERT INTO ESPECIALIDADE ( NUM, CERTIFICACAO, DESIGNACAO,DURACAO) VALUES (1,'FIS0','Fisioterapia', 20)
INSERT INTO ESPECIALIDADE ( NUM, CERTIFICACAO, DESIGNACAO,DURACAO) VALUES (2,'MASG','Massagem Desportiva', 30)
INSERT INTO ESPECIALIDADE ( NUM, CERTIFICACAO, DESIGNACAO,DURACAO) VALUES (3,'FIS1','Pilates Clinico', 40)
INSERT INTO ESPECIALIDADE ( NUM,  CERTIFICACAO, DESIGNACAO,DURACAO) VALUES (4,'FIS 0','Pos Parto', 30)


